### ISSUE TITLE
add a conversion from comma separated to tab separated

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/annotation_assistant#16]
@jayanthjaiswal @khoidt 

New version of libre office forces saving in comma separated format. Is it possible to convert the file to tab before check and before sending back? Not sure how else to handle this..

**Comment by khoidt** [comment]
Sure, I'll integrate this in the script, so all uploaded files will be automatically corrected and will fix all the files that have commas at the moment.

**Comment by khoidt** [comment]
With update 3c56b97, the files are now checked and corrected each time to_dict is updated and when an annotated text is uploaded.
Performs the following:
 - CSV > TSV.
 - ENSI > UTF-8.
 - Add '_' placeholders to empty columns.
 - Remove extra annotation suggestions.
 - Clear last three columns (`HEAD`, `DEPREL`, `MISC`).

@jayanthjaiswal, this should solve the CDLI-CoNLL > CoNLL-U data issues. The files in  [to_dict](https://github.com/cdli-gh/mtaac_gold_corpus/tree/workflow/morph/to_dict) (note that the active branch is `workflow`) were updated with cdli-gh/mtaac_gold_corpus@f1d32d7. 

@wangj619, please update the annotation assistant. You can do it by opening a terminal in the program's folder (`/annotation_assistant/`) and running `git pull origin master`.

@lukurkurra, you can try the same or we can schedule another remote session. :)
