### ISSUE TITLE
Workflow, adding a checker step

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/annotation_assistant#4]
I was looking at the readme and the code and I was wondering if it would be possible to add the checker step to the workflow? 

Feature: after annotating the text, the user should check the text (mpat -c) and update their annotations based on the errors and warnings until the checker passes, before sending back the text to the repo.

**Comment by khoidt** [comment]
Sure, I'll add this feature very soon.

**Comment by khoidt** [comment]
@epageperron, @wangj619, @zarpanitu 
I've updated the code to include a checker step and report errors in the GUI, if found. A text can be uploaded only if no errors are found.

Please, open the terminal in the program's folder and do `git pull origin master` to update the code.
