### ISSUE TITLE
Uploading a text, branch issues

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/annotation_assistant#8]
Hi,
I was able to login, download the text, annotate, then when I try to upload, nothing happens. Error as follows:

```
fatal: A branch named 'workflow' already exists.


[workflow 8f11aeb] Select P457733.conll for annotation by epageperron
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite morph/progress.json (76%)

To https://github.com/cdli-gh/mtaac_gold_corpus.git
   66760c0..8f11aeb  workflow -> workflow

reloading view
opening directory
opening web page
epp@waga-masta:/alty/data/annotation_assistant/scr$ [11205:11250:0530/080731.692614:ERROR:nss_util.cc(724)] After loading Root Certs, loaded==false: NSS error code: -8018
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[11205:11250:0530/080731.763339:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
Created new window in existing browser session.
epp@waga-masta:/alty/data/annotation_assistant/scr$ 


```

**Comment by epageperron** [comment]
Ok I just re-started main and I was able to upload. But the file was uploaded the workflow branch and the files are in the master branch? Is it possible to make sure either the branches are synchronized or that all the work is done in the same branch? The most up to date version of the annotated texts is in the master branch so creating the lexicon to annotate should be done from there and new next copied there as well. Let me know how you want to handle this.
Thanks !

**Comment by epageperron** [comment]
On second text, uploading worked without any problem

**Comment by epageperron** [comment]
Texts I have uploaded through the GUI, now only in workflow and not in master:

P457733
P131341

**Comment by khoidt** [comment]
The error has to do with the `-b` argument in the script's `git checkout -b workflow`. I used it to automatically create the `workflow` branch when it's missing. This can certainly be changed.

**Comment by khoidt** [comment]
@epageperron, if there are no additional problems, the issue can be closed.
